# List Comprehension

### 0부터 10까지 반복문

In [10]:
result = []

for i in range(10):
        result.append(i);

print(result)
print()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]



In [4]:
result2 = [i for i in range(10)]
print(result2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### 짝수 처리

In [ ]:
result = []

for i in range(10):
    if i % 2 == 0:
        result.append(i)

print(result)
print()

In [9]:
result2 = [i for i in range(10) if i % 2 == 0]
print(result2)

[0, 2, 4, 6, 8]


### 홀수 자리에 99 넣기

In [11]:
result = []

for i in range(10):
    if i % 2 == 0:
        result.append(i)
    else:
        result.append(99)
        
print(result)
print()

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]



In [14]:
result2 = [i if i % 2 == 0 else 99 for i in range(10)]
print(result2)

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]


### 이중 for문

In [16]:
result = []
case1 =  ['A', 'B', 'C']
case2 =  ['A', 'B', 'C']

for i in case1:
    for j in case2:
        result.append(i + j)
print(result)

['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']


In [18]:
result2  = [i + j for i in case1 for j in case2]
print(result2)


['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']


### 이중 for문 중복제거

In [19]:
result2  = [i + j for i in case1 for j in case2 if i != j]
print(result2)


['AB', 'AC', 'BA', 'BC', 'CA', 'CB']


# Numpy

In [22]:
import numpy as np

In [23]:
a1 = np.array([0, 1, 2, 3, 4, 5])
print(a1)

[0 1 2 3 4 5]


In [25]:
print(type(a1))

<class 'numpy.ndarray'>


In [28]:
print(a1.dtype)

int32


In [29]:
list1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [30]:
list2 = np.array(list1)
print(list2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


In [35]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [37]:
a = np.arange(12).reshape(4, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
a = np.arange(12).reshape(4, -1)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
a = np.arange(12).reshape(-1, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
a = np.arange(11).reshape(4, -1)
print(a)

ValueError: cannot reshape array of size 11 into shape (4,newaxis)

### 1부터 10까지 10등분하기

In [42]:
a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [43]:
a = np.linspace(1, 10, 8)
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [44]:
a = np.linspace(0, np.pi, 20)
print(a)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [48]:
a1 = np.zeros(10, int)
print(a1)
print()
a2 = np.zeros((3, 4), int)
print(a2)
print()
a3 = np.ones(5)
print(a3)
print()
a4 = np.ones((3, 5))
print(a4)
print()
a5 = np.eye(3)
print(a5)

[0 0 0 0 0 0 0 0 0 0]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
list1 = [10, 20 , 30, 40]
list2 = [1, 2 , 3, 4]
print(list1+ list2)


[10, 20, 30, 40, 1, 2, 3, 4]


### element-wise operation

In [50]:
a1 = np.array(list1)
a2 = np.array(list2)
print(a1 + a2)

[11 22 33 44]


In [51]:
print(a1 > a2)

[ True  True  True  True]


In [53]:
a1 = np.arange(1, 6)

print(a1.sum()) # 합
print(a1.mean()) # 평균값
print(a1.std()) # 표준평균
print(a1.var()) # 분산
print(a1.min()) # 최대
print(a1.max()) # 최소
print(a1.cumsum()) # 누적 합
print(a1.cumprod()) # 누적 곱셈

15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [54]:
a = np.array([0, 1, 2, 3]).reshape(2, 2)
print(a)

b = np.array([3, 2, 0, 1]).reshape(2, 2)
print(b)
print('-'*20)
print(a.dot(b)) # 행렬곲
print(np.dot(a, b)) # 행렬곲
print('-'*20)
print(np.transpose(a)) # 전치행렬
print(a.transpose()) # 전치행렬
print(a.T) # 전치행렬
print('-'*20)
print(np.linalg.inv(a)) # 역행렬
print(np.linalg.det(a)) # 행렬식

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]
--------------------
[[0 1]
 [6 7]]
[[0 1]
 [6 7]]
--------------------
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
--------------------
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0


In [60]:
a = np.array([0, 10, 20, 30, 40, 50])
print(a[[1, 3, 4]])

b = np.arange(10, 100, 10).reshape(3, 3)
print(b)

print(b[0, 2])

b[2, 2] = 97
print(b)

print(b[1])

print('-'*20)

b[1] = np.array([45, 55, 65])
print(b)

b[2] = [75, 85, 95]
print(b)

print('-'*20)

print(b[[0, 2], [0, 1]])

[10 30 40]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 30]
 [40 50 60]
 [70 80 97]]
[40 50 60]
--------------------
[[10 20 30]
 [45 55 65]
 [70 80 97]]
[[10 20 30]
 [45 55 65]
 [75 85 95]]
--------------------
[10 85]


In [62]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])
print(a[(a % 2) == 0])

[4 5 6]
[2 4 6]


In [63]:
a = np.array([0, 10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])
print(a[2:])
a[2:5] = np.array([25, 35, 45])
print(a)

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]


In [66]:
a = np.arange(10, 100, 10).reshape(3, 3)
print(a)
print(a[1:3, 1:3])
print(a[:3, 1:])
print(a[1][0:2])
a[0:2, 1:3] = np.array([[25, 35], [55, 65]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]


ValueError: could not broadcast input array from shape (2,2) into shape (1,2)